### 회원가입 (고객)
POST http://localhost:8081/signup/customer
Content-Type: application/json

{
  "birth": "1994-01-19",
  "email": "tot0119@naver.com",
  "name": "오동건",
  "password": "123",
  "phone": "0100000000"
}
### 이메일 인증 (고객)
GET http://localhost:8081/signup/customer/verify?email=tot0119@naver.com&code=1XHyorj19B


### 로그인 (고객)
POST http://localhost:8081/signin/customer
Content-Type: application/json

{
  "email": "tot0119@naver.com",
  "password": "123"
}

### 회원 정보 조회 (고객)
GET http://localhost:8081/customer/getInfo
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpYVUvQzVDcngwMnVOM1RXT1VNSExNT3lOMjM1TWFlSEx0dkdMYjc3QmNVPSIsImp0aSI6IjNFN2xQeUpIOTJENzZ3bjNhNVpGS0E9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAyNTk5NzEsImV4cCI6MTY4MDM0NjM3MX0.J4pye-a3PF_pk38XqqYf8KI5y6F8F3nU-3tWpxNT_T4


### 잔액 변경 (고객)
POST http://localhost:8081/customer/balance
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpYVUvQzVDcngwMnVOM1RXT1VNSExNT3lOMjM1TWFlSEx0dkdMYjc3QmNVPSIsImp0aSI6IjNFN2xQeUpIOTJENzZ3bjNhNVpGS0E9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODAyNTk5NzEsImV4cCI6MTY4MDM0NjM3MX0.J4pye-a3PF_pk38XqqYf8KI5y6F8F3nU-3tWpxNT_T4

{
  "from": "server",
  "message": "잔액 충전",
  "money": 50000
}
#################################
